services:

  db:
    container_name: auth_db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=raHwQcbGUy7Y8I7ImVelLxaICDeF4ikH
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data: { }
