services:

  auth_app_service:
    container_name: auth_service_app
    build: .
    image: auth_service:latest
    restart: on-failure:3
    depends_on:
      - auth_db_service
    ports:
      - "8081:8081"

  auth_db_service:
    container_name: auth_service_db
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=raHwQcbGUy7Y8I7ImVelLxaICDeF4ikH
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data: { }
