server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: master
    password: raHwQcbGUy7Y8I7ImVelLxaICDeF4ikH
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
auth-server:
  jwt-private-key-password: 6le/Hb30zwXKHQ1WYo7mHnw7v2G+8UCX/ewoou+661k=