server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://auth_db_service:5432/auth_db
    username: master
    password: raHwQcbGUy7Y8I7ImVelLxaICDeF4ikH
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
